server:
  port: 11111
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/digital_my
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
